version: '3.4'

services:
  sgfapi:
    image: sgf-api
    build:
      context: sgf-api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "bin/server.js"]
