version: '3.4'
services:
  sgfapi:
    image: sgfapi
    build:
      context: sgf-api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
