INSERT INTO account_plans (
    number,
    description,
    writable,
    type,
    class,
    state,
    created_at,
    updated_at
) VALUES
('1', 'MEIOS FINANCEIROS', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('11', 'Caixa', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('12', 'Bancos', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('121', 'Depósitos à ordem', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('123', 'Depósitos a prazo', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('3', 'INVESTIMENTOS DE CAPITAL', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('32', 'Activos tangíveis', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('33', 'Activos intangíveis', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('34', 'Investimentos em curso', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('36', 'Activos tangíveis de investimento', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('38', 'Amortizações acumuladas', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('382', 'Activos tangíveis', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('383', 'Activos intangíveis', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('4', 'CONTAS A RECEBER E CONTAS A PAGAR', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('41', 'Clientes', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('411', 'Clientes c/c', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('42', 'Fornecedores', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('421', 'Fornecedores c/c', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('43', 'Empréstimos obtidos', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('44', 'Estado', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('45', 'Outros devedores', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('46', 'Outros credores', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('48', 'Provisões', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('49', 'Acréscimos e diferimentos', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('51', 'Capital', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('59', 'Resultados transitados', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('6', 'GASTOS E PERDAS', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('61', 'Custo dos inventários', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('62', 'Gastos com o pessoal', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('63', 'Fornecimentos e serviços de terceiros', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('632', 'Fornecimentos e serviços', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('64', 'Transferências Correntes', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('66', 'Exercicios Findos', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('661', 'Retroactivos Salariais do Exercicio Corrente para Pessoal Civil', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('662', 'Retroactivos de Bens e Servicos', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('68', 'Outros gastos e perdas operacionais', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('683', 'Perdas em investimentos de capital', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('69', 'Gastos e perdas financeiros', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('7', 'RENDIMENTOS E GANHOS', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('72', 'Receitas', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('76', 'Outros rendimentos e ganhos operacionais', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('78', 'Rendimentos e ganhos financeiros', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('81', 'Resultados', 'controll', 'financial', 'A', 1, NOW(), NOW());
