INSERT INTO account_plan_years (
    year,
    description,
    state,
    created_at,
    updated_at
) VALUES
(2024, 'Ano fiscal 2024',1, NOW(), NOW());
commit;

-- Plano de conta financeiro das contas de controle
INSERT INTO account_plans (
    number,
    description,
    writable,
    type,
    class,
    state,
    created_at,
    updated_at
) VALUES
('1', 'MEIOS FINANCEIROS', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('11', 'Caixa', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('12', 'Bancos', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('121', 'Depósitos à ordem', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('123', 'Depósitos a prazo', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('3', 'INVESTIMENTOS DE CAPITAL', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('32', 'Activos tangíveis', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('33', 'Activos intangíveis', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('34', 'Investimentos em curso', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('36', 'Activos tangíveis de investimento', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('38', 'Amortizações acumuladas', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('382', 'Activos tangíveis', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('383', 'Activos intangíveis', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('4', 'CONTAS A RECEBER E CONTAS A PAGAR', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('41', 'Clientes', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('411', 'Clientes c/c', 'controll', 'financial', 'C', 1, NOW(), NOW()),
('42', 'Fornecedores', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('421', 'Fornecedores c/c', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('43', 'Empréstimos obtidos', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('44', 'Estado', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('45', 'Outros devedores', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('46', 'Outros credores', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('48', 'Provisões', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('49', 'Acréscimos e diferimentos', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('51', 'Capital', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('59', 'Resultados transitados', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('6', 'GASTOS E PERDAS', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('61', 'Custo dos inventários', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('62', 'Gastos com o pessoal', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('63', 'Fornecimentos e serviços de terceiros', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('632', 'Fornecimentos e serviços', 'controll', 'financial', 'C', 1, NOW(), NOW()),
('64', 'Transferências Correntes', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('66', 'Exercicios Findos', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('661', 'Retroactivos Salariais do Exercicio Corrente para Pessoal Civil', 'controll', 'financial', 'C', 1, NOW(), NOW()),
('662', 'Retroactivos de Bens e Servicos', 'controll', 'financial', 'C', 1, NOW(), NOW()),
('68', 'Outros gastos e perdas operacionais', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('683', 'Perdas em investimentos de capital', 'controll', 'financial', 'C', 1, NOW(), NOW()),
('69', 'Gastos e perdas financeiros', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('7', 'RENDIMENTOS E GANHOS', 'controll', 'financial', 'A', 1, NOW(), NOW()),
('72', 'Receitas', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('76', 'Outros rendimentos e ganhos operacionais', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('78', 'Rendimentos e ganhos financeiros', 'controll', 'financial', 'B', 1, NOW(), NOW()),
('81', 'Resultados', 'controll', 'financial', 'B', 1, NOW(), NOW());
commit;

-- Entradas - Saldos do plano de conta financeiro das contas de controle
INSERT INTO `account_plan_entries` 
(`start_posting_month`, `end_posting_month`, `reserve_percent`, 
`initial_allocation`, `final_allocation`, `account_plan_year_id`, 
`account_plan_id`, `parent_id`, `state`, `created_by`, `created_at`, 
`updated_by`, `updated_at`, `account_plan_number`) 
VALUES 
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='1'), NULL, 1, NULL, NULL, NULL, NULL, 1),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='11'), (select parent.id from account_plan_entries parent where parent.account_plan_number='1'), 1, NULL, NULL, NULL, NULL, 11),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='12'), (select parent.id from account_plan_entries parent where parent.account_plan_number='1'), 1, NULL, NULL, NULL, NULL, 12),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='121'), (select parent.id from account_plan_entries parent where parent.account_plan_number='12'), 1, NULL, NULL, NULL, NULL, 121),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='123'), (select parent.id from account_plan_entries parent where parent.account_plan_number='12'), 1, NULL, NULL, NULL, NULL, 123),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='3'), NULL, 1, NULL, NULL, NULL, NULL, 3),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='32'), (select parent.id from account_plan_entries parent where parent.account_plan_number='3'), 1, NULL, NULL, NULL, NULL, 32),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='33'), (select parent.id from account_plan_entries parent where parent.account_plan_number='3'), 1, NULL, NULL, NULL, NULL, 33),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='34'), (select parent.id from account_plan_entries parent where parent.account_plan_number='3'), 1, NULL, NULL, NULL, NULL, 34),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='36'), (select parent.id from account_plan_entries parent where parent.account_plan_number='3'), 1, NULL, NULL, NULL, NULL, 36),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='38'), (select parent.id from account_plan_entries parent where parent.account_plan_number='3'), 1, NULL, NULL, NULL, NULL, 38),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='382'), (select parent.id from account_plan_entries parent where parent.account_plan_number='38'), 1, NULL, NULL, NULL, NULL, 382),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='383'), (select parent.id from account_plan_entries parent where parent.account_plan_number='38'), 1, NULL, NULL, NULL, NULL, 383),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='4'), NULL, 1, NULL, NULL, NULL, NULL, 4),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='41'), (select parent.id from account_plan_entries parent where parent.account_plan_number='4'), 1, NULL, NULL, NULL, NULL, 41),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='411'), (select parent.id from account_plan_entries parent where parent.account_plan_number='41'), 1, NULL, NULL, NULL, NULL, 411),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='42'), (select parent.id from account_plan_entries parent where parent.account_plan_number='4'), 1, NULL, NULL, NULL, NULL, 42),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='421'), (select parent.id from account_plan_entries parent where parent.account_plan_number='42'), 1, NULL, NULL, NULL, NULL, 421),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='43'), (select parent.id from account_plan_entries parent where parent.account_plan_number='4'), 1, NULL, NULL, NULL, NULL, 43),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='44'), (select parent.id from account_plan_entries parent where parent.account_plan_number='4'), 1, NULL, NULL, NULL, NULL, 44),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='45'), (select parent.id from account_plan_entries parent where parent.account_plan_number='4'), 1, NULL, NULL, NULL, NULL, 45),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='46'), (select parent.id from account_plan_entries parent where parent.account_plan_number='4'), 1, NULL, NULL, NULL, NULL, 46),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='48'), (select parent.id from account_plan_entries parent where parent.account_plan_number='4'), 1, NULL, NULL, NULL, NULL, 48),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='49'), (select parent.id from account_plan_entries parent where parent.account_plan_number='4'), 1, NULL, NULL, NULL, NULL, 49),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='51'), NULL, 1, NULL, NULL, NULL, NULL, 51),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='59'), NULL, 1, NULL, NULL, NULL, NULL, 59),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='6'), NULL, 1, NULL, NULL, NULL, NULL, 6),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='61'), (select parent.id from account_plan_entries parent where parent.account_plan_number='6'), 1, NULL, NULL, NULL, NULL, 61),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='62'), (select parent.id from account_plan_entries parent where parent.account_plan_number='6'), 1, NULL, NULL, NULL, NULL, 62),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='63'), (select parent.id from account_plan_entries parent where parent.account_plan_number='6'), 1, NULL, NULL, NULL, NULL, 63),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='632'), (select parent.id from account_plan_entries parent where parent.account_plan_number='63'), 1, NULL, NULL, NULL, NULL, 632),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='64'), (select parent.id from account_plan_entries parent where parent.account_plan_number='6'), 1, NULL, NULL, NULL, NULL, 64),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='66'), (select parent.id from account_plan_entries parent where parent.account_plan_number='6'), 1, NULL, NULL, NULL, NULL, 66),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='661'), (select parent.id from account_plan_entries parent where parent.account_plan_number='66'), 1, NULL, NULL, NULL, NULL, 661),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='662'), (select parent.id from account_plan_entries parent where parent.account_plan_number='66'), 1, NULL, NULL, NULL, NULL, 662),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='68'), (select parent.id from account_plan_entries parent where parent.account_plan_number='6'), 1, NULL, NULL, NULL, NULL, 68),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='683'), (select parent.id from account_plan_entries parent where parent.account_plan_number='68'), 1, NULL, NULL, NULL, NULL, 683),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='69'), (select parent.id from account_plan_entries parent where parent.account_plan_number='6'), 1, NULL, NULL, NULL, NULL, 69),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='7'), NULL, 1, NULL, NULL, NULL, NULL, 7),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='72'), (select parent.id from account_plan_entries parent where parent.account_plan_number='7'), 1, NULL, NULL, NULL, NULL, 72),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='76'), (select parent.id from account_plan_entries parent where parent.account_plan_number='7'), 1, NULL, NULL, NULL, NULL, 76),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='78'), (select parent.id from account_plan_entries parent where parent.account_plan_number='7'), 1, NULL, NULL, NULL, NULL, 78),
(1, 12, 0, 0, 0, (select id from account_plan_years where year=2024), (select acc.id from account_plans acc where acc.number='81'), NULL, 1, NULL, NULL, NULL, NULL, 81);
commit;